baseURL = "https://commons.garden/"
languageCode = "en-us"
title = "Commons Garden"
description = "Decolonize your attention"
publishDir = "docs"
logo = "logo-big.svg"
category = ["article", "initiative", "organization", "spec", "team", "volunteer", "wireframe"]